### ISSUE TITLE
error when logging in when using auth0

### ISSUE THREAD

**Issue by padmick** [openanalytics/shinyproxy#111]
Hi,
Using the documented auth flow i seem to be triggering an exception via auth0. The flow seems to working correctly on the auth0 side but the client seems to trigger an exception:

`java.lang.StackOverflowError:` null
        at java.lang.ReflectiveOperationException.<init>(Unknown Source) ~[na:1.8.0_171]
        at java.lang.reflect.InvocationTargetException.<init>(Unknown Source) ~[na:1.8.0_171]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_171]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.sun.proxy.$Proxy77.authenticate(Unknown Source) ~[na:na]
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199) ~[spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:502) ~[spring-security-config-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_171]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.sun.proxy.$Proxy77.authenticate(Unknown Source) ~[na:na]
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199) ~[spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:502) ~[spring-security-config-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_171]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at com.sun.proxy.$Proxy77.authenticate(Unknown Source) ~[na:na]``

**Comment by fmichielssen** [comment]
Hi @padmick ,

The authenticator keeps calling itself, resulting in an endless loop.
This might be a configuration issue. Can you post your `application.yml`?

**Comment by padmick** [comment]
think i have it :D ill close this issue thanks!

**Comment by Five-Cents** [comment]
Mind sharing your solution? I'm having a very similar issue.

**Comment by padmick** [comment]
Sure it was the rules I had written in auth 0 for the application were causing issues
Removing the extra whitelisting rules I had written within auto 0 removed the issue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iclarke** [comment]
Hi, I am having the exact same issue however I do no have any whitelisting rules in place so this cannot be the cause of the issue for me. My Application.yml file is as below : 

Any help would be greatly appreciated - thanks in advance !

proxy:
  title: blabla Analytics Hub
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  #useForwardHeaders: true
  authentication: openid
  openid:
   auth-url: https://blabladatatools.eu.auth0.com/authorize
   token-url: https://blabladatatools.eu.auth0.com/oauth/token
   jwks-url: https://blabladatatools.eu.auth0.com/.well-known/jwks.json
   client-id: id
   client-secret: secret
   #roles-claim: https://shinyproxy.io/shinyproxy_roles
   #logout-url: https://blabladatatools.eu.auth0.com/v2/logout?returnTo=http%3A%2F%2Fwww.blabladatatools.com
   #username-attribute: email

  docker:
   cert-path: /home/none
   url: http://localhost:2375
   port-range-start: 20000
   container-protocol: https
   
  
  specs:
  - id: blabla_app
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shinydockerimage')"]
    container-image: blabla_shinyapp

#logging:
#  level:
#    org.springframework.security: debug
#  file:
#    shinyproxy.log
    
logging:
  file:
    shinyproxy.log
    
server:
  useForwardHeaders: true
