### ISSUE TITLE
Shinyproxy landing on `/error` with `200 OK` status code after login

### ISSUE THREAD

**Issue by freaknils** [openanalytics/shinyproxy#166]
Hi,

I am currently running 3 Shinyproxy instances. All are configured in the same way:
```
---
proxy:
  title: <name>
  hide-navbar: true
  template-path: <template path>
  landing-page: /
  contextPath: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-backend: docker
  container-log-path: /var/log/shinyproxy/container
  authentication: ldap
  ldap: {
    "group-search-base": "ou=group",
    "group-search-filter": "(member={0})",
    "manager-dn": "<dn>",
    "manager-password": "XXXXXXXXXXXX",
    "starttls": "simple",
    "url": "ldap://<url>,
    "user-dn-pattern": "cn={0},ou=user"
}
  docker:
    cert-path: /home/none
    port-range-start: 20000
  specs: [
    {
        "access-groups": [
            "admins"
        ],
        "container-cmd": [
            "R",
            "-e",
            "shiny::runApp(appDir = '<path>', port = 3838, host = '0.0.0.0')"
        ],
        "container-image": "<custom-image>",
        "container-volumes": [
            "<path>:ro"
        ],
        "description": "<name>",
        "display-name": "<name>",
        "id": "<name>"
    }
]

logging:
  file:
    /var/log/shinyproxy/shinyproxy.log
```

Login works well, but after login I am redirected to `/error` with status code 200.
```
Error

Status code: 200
Message: OK
Stack Trace:
n/a
```
If I open `/app/intranet` manually the doker container is started and everything works well.

Any idears? On other instances configured the same everything works well.
Thanks!

**Comment by freaknils** [comment]
I have fixed this by using an redirection in Nginx proxy

**Comment by nbbn** [comment]
Hi, I feel redirection in nginx as workaround. Problem still exists. From my experience, this is a problem with missing support files like fonts, js, css, etc. It shouldn't be manifested as error with code 200.

I'm not sure I can reopen this issue, can you do it for me?

**Comment by tverbeke** [comment]
@nbbn @freaknils Can you confirm this is fixed in version 2.3.1?

**Comment by django-datama** [comment]
We still have this bug...!

**Comment by creativde** [comment]
I also have this bug, and it only occurs when I add a template-path. The login page works but I get the same error when logging in - fixed when refreshing.

Seems to be a missing file (fonts / js / css issue). Is there a folder that has all the relevant docs for template-path when using containerproxy?

**Comment by django-datama** [comment]
Can you re-open this issue ? @freaknils @tverbeke

**Comment by LEDfan** [comment]
Hi @django-datama @creativde @nbbn 

Unfortunately, I'm not able to reproduce this issue. I tried with various broken and outdated templates and wrong config, but it all results in proper error messages. Of course I"m interested in fixing this issue, but I suspect it may have to do something with your templates. Could one of you provide me with your (redacted) templates? Please also mention your ShinyProxy version and in which way your run ShinyProxy (e.g. using the Jar, docker, kubernetes etc).
If you prefer to send me the files privately, you can send an e-mail to github at ledfan dot be.
Thanks!

**Comment by nbbn** [comment]
HI, I upgraded my shinyproxy to the newest version and rewritten my template, so I don't have this problem anymore.
IMO problem is mainly with paths to external resources inside template (like fonts, css, etc.). I will try to find my older template and check on which versions it trigger this error messages.

**Comment by django-datama** [comment]
Hi @nbbn @LEDfan, @freaknils and @tverbeke,

We are running shinyproxy v2.0.0.RELEASE (java -jar in a custom docker container),  and it's seems that some resources are not loaded properly (attached image). As mentioned by @nbbn, we are going to upgrade our version and change our config and see how it works.

Thank you @LEDfan and @nbbn for your help.
We'll keep you informed.

Kind regards,

![Capture d’écran 2021-02-19 à 19 27 12](https://user-images.githubusercontent.com/51702254/108546432-63aa8c80-72e9-11eb-8991-19975ce0bc36.png)

**Comment by LEDfan** [comment]
Thanks for investigating, would be helpful if I can reproduce the issue.

@django-datama regarding the messages in your screenshots: those aren't errors. It simply are messages by the Spring framework that indicates how URLs are handled. For example, that `/error` is handled by the `ErrorController` etc.
You can ignore these messages.

**Comment by django-datama** [comment]
We found a way to replicate this issue.

Just go to /logout (without any prior login) using keycloak and then login, it'll throw you a Error with a 200 code !

Sorry, it's been a year !

**Comment by django-datama** [comment]
FYI

```
java.lang.NullPointerException: null
	at eu.openanalytics.containerproxy.auth.impl.OpenIDAuthenticationBackend.lambda$getLogoutSuccessHandler$0(OpenIDAuthenticationBackend.java:165) ~[containerproxy-0.8.10.jar!/:0.8.10]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:111) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.3.9.RELEASE.jar!/:5.3.9.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:97) ~[spring-boot-actuator-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at eu.openanalytics.containerproxy.util.ProxyMappingManager$ProxyPathHandler.handleRequest(ProxyMappingManager.java:160) ~[containerproxy-0.8.10.jar!/:0.8.10]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.server.handlers.SameSiteCookieHandler.handleRequest(SameSiteCookieHandler.java:97) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) ~[undertow-servlet-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841) ~[undertow-core-2.2.8.Final.jar!/:2.2.8.Final]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) ~[xnio-api-3.8.4.Final.jar!/:3.8.4.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2022-01-20 21:51:03.840  INFO 1 --- [  XNIO-1 task-1] e.o.containerproxy.service.UserService   : User logged in [user: django]
```

**Comment by tverbeke** [comment]
Thank you, @django-datama, for coming back on this. Can you indicate which version you are experiencing this with? Does this happen with the latest version (2.6.0)?

**Comment by LEDfan** [comment]
Hi @django-datama 

I'm able to reproduce the issue with ContainerProxy 0.8.10 (ShinyProxy 2.6.0). This will be fixed in the next-release.
Note that this issue was introduced in ShinyProxy 2.6.0, so it is not the exact same issue as in the rest of this ticket. I'm not able to reproduce a similar issue with 2.5.1 (i.e. going to /logout without logging in and then trying to login).
