### ISSUE TITLE
NPE and Status 500 when serving favicon.ico from root context of SAML authed app

### ISSUE THREAD

**Issue by mskyttner** [openanalytics/shinyproxy#194]
My `application.yaml` has this entry:

```
proxy:
  favicon-path: favicon.ico
```
And the shinyproxy container has this file present inside the container at `/opt/shinyproxy/favicon.ico` in the same directory as the shinproxy.jar

I use SAML authentication and when accessing the application I get a 500 error when the favicon.ico is to be served:

```
Error

Status code: 500

Message: An unexpected server error occurred

Stack Trace:
java.lang.NullPointerException
at eu.openanalytics.containerproxy.ui.FaviconConfig$CachedFaviconHttpRequestHandler.handleRequest(FaviconConfig.java:90)
at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:53)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at org.springframework.security.saml.metadata.MetadataGeneratorFilter.doFilter(MetadataGeneratorFilter.java:87)
```

**Comment by mskyttner** [comment]
Could this favicon.ico serving error be related to SAML authentication being active and as a consequence be caused by the MetadataGeneratorFilter?

"In case the application is configured to automatically generate metadata, the generation occurs upon first invocation of this filter (first request made to the server)." says https://docs.spring.io/spring-security-saml/docs/current/api/org/springframework/security/saml/metadata/MetadataGeneratorFilter.html

**Comment by LEDfan** [comment]
Hi, this should be fixed in ShinyProxy 3.1.0, which we released today. Thanks again for your reporting this bug! I'll close this issue, please open a new issue or re-open this issue if you are still experiencing an issue.
