### ISSUE TITLE
Failed to start container when using docker swarm (1 manager + 1 worker)

### ISSUE THREAD

**Issue by PauloJhonny** [openanalytics/shinyproxy#214]
Hello, I am using shinyproxy with docker swarm (1 manager + 1 worker).

Authentication works well and I can access the index page, but I cannot access any of the available apps. An error occurs when I try to access them.

If I don't join a worker in the cluster, everything works perfectly.

Here is some information:

## 1. logs:
```
Error
Status code: 500

Message: Failed to start container

Stack Trace:
eu.openanalytics.containerproxy.ContainerProxyException: Failed to start container
at eu.openanalytics.containerproxy.backend.AbstractContainerBackend.startProxy(AbstractContainerBackend.java:113)
at eu.openanalytics.containerproxy.service.ProxyService.startProxy(ProxyService.java:213)
at eu.openanalytics.shinyproxy.controllers.AppController.getOrStart(AppController.java:109)
at eu.openanalytics.shinyproxy.controllers.AppController.startApp(AppController.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64)
at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
at eu.openanalytics.containerproxy.util.ProxyMappingManager$ProxyPathHandler.handleRequest(ProxyMappingManager.java:159)
at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 12
at java.lang.String.substring(String.java:1963)
at eu.openanalytics.containerproxy.backend.docker.DockerSwarmBackend.calculateTarget(DockerSwarmBackend.java:154)
at eu.openanalytics.containerproxy.backend.docker.DockerSwarmBackend.startContainer(DockerSwarmBackend.java:140)
at eu.openanalytics.containerproxy.backend.AbstractContainerBackend.doStartProxy(AbstractContainerBackend.java:129)
at eu.openanalytics.containerproxy.backend.AbstractContainerBackend.startProxy(AbstractContainerBackend.java:110)
... 95 more
```
## 2. docker swarm working:

```
**sudo docker node ls**

ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
m44fnumvmbyd5n2ficv0sndf4     betashiny           Ready               Active                                  19.03.8
6ubew9bwuhgpbir2d4zcanat6 *   shinyproxynidev     Ready               Active              Leader              19.03.8


** sudo docker info**
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 6
  Paused: 0
  Stopped: 2
 Images: 82
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 6ubew9bwuhgpbir2d4zcanat6
  Is Manager: true
  ClusterID: u9ewfsk81ga4beso5gxrhwigp
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
 Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.56.1.44
  Manager Addresses:
   10.56.1.44:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-66-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.66GiB
 Name: shinyproxynidev
 ID: 7AN5:S2FA:LHWH:3SBG:36OL:ELJW:LMQG:U5KO:QCN3:YEX5:YFOH:NRKG
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 92
  Goroutines: 227
  System Time: 2020-07-01T14:31:24.071575904-03:00
  EventsListeners: 6
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://127.0.0.1:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
```

## 3. communication between servers - OK:

```
**ping betashiny**

PING betashiny (10.56.0.68) 56(84) bytes of data.
64 bytes from 10.56.0.68 (10.56.0.68): icmp_seq=1 ttl=63 time=0.536 ms
64 bytes from 10.56.0.68 (10.56.0.68): icmp_seq=2 ttl=63 time=0.314 ms
64 bytes from 10.56.0.68 (10.56.0.68): icmp_seq=3 ttl=63 time=0.331 ms
64 bytes from 10.56.0.68 (10.56.0.68): icmp_seq=4 ttl=63 time=0.305 ms
64 bytes from 10.56.0.68 (10.56.0.68): icmp_seq=5 ttl=63 time=0.336 ms
^C
--- betashiny ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4066ms
rtt min/avg/max/mdev = 0.305/0.364/0.536/0.088 ms

**ping shinyproxynidev**

ping shinyproxynidev
PING shinyproxynidev (10.56.1.44) 56(84) bytes of data.
64 bytes from 10.56.1.44: icmp_seq=1 ttl=63 time=1.38 ms
64 bytes from 10.56.1.44: icmp_seq=2 ttl=63 time=0.424 ms
64 bytes from 10.56.1.44: icmp_seq=3 ttl=63 time=0.385 ms
64 bytes from 10.56.1.44: icmp_seq=4 ttl=63 time=0.407 ms
64 bytes from 10.56.1.44: icmp_seq=5 ttl=63 time=0.470 ms
64 bytes from 10.56.1.44: icmp_seq=6 ttl=63 time=0.345 ms
^C
--- shinyproxynidev ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 4999ms
rtt min/avg/max/mdev = 0.345/0.568/1.382/0.366 ms
```

## 4. docker-compose file:

```yaml
version: "3.6"
services:
  shinyproxy:
    image: datanovia/shinyproxy
    container_name: dnv_shinyproxy
    restart: always
    build: ./s3i
    networks:
      - dnv-net
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./shinyproxy-logs/s3i/:/log"
      - "./shinyproxy-logs/s3i/:/container-logs"
      - "./s3i/application.yml:/opt/shinyproxy/application.yml"
      - "./s3i/templates:/opt/shinyproxy/templates"
  app1:
    image: app1-docker
    container_name: dnv_app1
    build: ./shinyapps/app1-docker
    networks:
      - dnv-net
  app2:
    image: app2-docker
    container_name: dnv_app2
    build: ./shinyapps/app2-docker
    networks:
      - dnv-net
  app3:
    image: app3-docker
    container_name: dnv_app3
    build: ./shinyapps/app3-docker
    networks:
      - dnv-net

networks:
  dnv-net:
    name: dnv-net
```

## 5. application file:

```yaml
server:
  contextPath: /s3i
  servlet:
    context-path: /s3i

proxy:
  title: S3i
  landing-page: /
  hide-navbar: false
  logo-url: file:///opt/shinyproxy/templates/fragments/assets/img/name.png
  template-path: ./templates/2col
  container-log-path: /log/container
  port: 8080
  container-wait-time: 60000
  heartbeat-timeout: 30000
  heartbeat-rate: 10000
  authentication: ldap
  admin-groups: admin
  ldap:
    url: XXXXXXXXXXXXXXXXXX
    manager-dn: XXXXXXXXXXXXXX
    manager-password: XXXXXXXXXXXXXX
    user-search-filter: XXXXXXXXXXXXXX
    group-search-filter: XXXXXXXXXXXXX
    group-search-base: XXXXXXXXXXXX
  container-backend: docker-swarm
  docker:
      internal-networking: true
      container-network: dnv-net
  specs:
  - id: app1
    display-name: yyyyyyyyyyyyyyyyyyyy
    description: yyyyyyyyyyyyyyyyyyyyyy
    container-cmd: ["R", "-e", "shiny::runApp('/root/app1')"]
    container-image: app1-docker
    container-cpu-limit: 1
    container-network: "${proxy.docker.container-network}"
    access-groups: [admin]
  - id: app2
    display-name: yyyyyyyyyyyyyyyyyyyyyyy
    description: yyyyyyyyyyyyyyyyyyyyyy
    container-cmd: ["R", "-e", "shiny::runApp('/root/app2')"]
    container-image: app2-docker
    container-cpu-limit: 1
    container-network: "${proxy.docker.container-network}"
    access-groups: [admin]
  - id: app3
    display-name: yyyyyyyyyyyyyyyy
    description: yyyyyyyyyyyyyyyyyyyyyyyy
    container-cmd: ["R", "-e", "shiny::runApp('/root/app3')"]
    container-image: app3-docker
    container-cpu-limit: 1
    container-network: "${proxy.docker.container-network}"
    access-groups: [admin]

logging:
  file:
    /log/server/shinyproxy.log
```
Thank you.

**Comment by PauloJhonny** [comment]
One more info. It looks like the images are being rejected on the worker. I don't know what am I supposed to do.

```
 sudo docker service ps --no-trunc dev_app1
ID                          NAME                 IMAGE                    NODE                DESIRED STATE       CURRENT STATE             ERROR                                     PORTS
yk9tpyqu05boqw82jag6mkp3y   dev_app1.1       app1-docker:latest   shinyproxynidev     Running             Running 1 second ago
q4ic2jsurvonaezf4jaocnghf    \_ dev_app1.1   app1-docker:latest   betashiny       Shutdown            Rejected 11 seconds ago   "No such image: app1-docker:latest"
dgkcsbmm2zlwtnpijkdd6kc25    \_ dev_app1.1   app1-docker:latest   betashiny       Shutdown            Rejected 16 seconds ago   "No such image: app1-docker:latest"
ob0u4sot2gumrp4bax8uuh8dm    \_ dev_app1.1   app1-docker:latest   betashiny       Shutdown            Rejected 21 seconds ago   "No such image: app1-docker:latest"
c69lpcoied2xxiaesro56ei68    \_ dev_app1.1   app1-docker:latest   betashiny       Shutdown            Rejected 26 seconds ago   "No such image: app1-docker:latest"
```

**Comment by keatonwilson** [comment]
Any updates on this? I'm getting the same error (though my structure is a bit different - one of my apps works , but another generates the error above)?

**Comment by ziyunxiao** [comment]
The error "No such image" identifies the root cause.

Is your image in the public repo(no auth) or private(need auth)? If it is in private, this is the limitation of the current version.
The workaround is to pull the image on all nodes( as part of the deployment process for an app).

If it is a public repo, check why the docker swarm could not download the image. You use the docker stack deploy command to create a service with your image for troubleshooting.
