### ISSUE TITLE
File upload error 25461 for io.undertow.proxy

### ISSUE THREAD

**Issue by GuoanQi1996** [openanalytics/shinyproxy#215]
Dear community,
I am deploying a shiny app using shinyproxy 2.3.1. Here after is my procedure.
1) I installed the java SDK and docker in linux (centos) server, then downloaded the shinyproxy .rpm and .java.
2) I made a docker mirrior contains my shiny app, since i had a self-made welcome web page, so i used shiny-server to hold my shiny app in the container.
3) This is my application.yml, and the startup command for docker mirror is, as shown below, 'shiny-server'.
`_proxy:
  title: EigenGWAS Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /app/EigenGWAS
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 600000
  port: 80
  authentication: none
  admin-groups: scientists

  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
   - id: EigenGWAS
     display-name: EigenGWAS
     container-cmd: ["shiny-server"]
     container-image: eigengwas:v1
     container-cpu-limit: 1`_
4) java -jar shinyproxy-2.3.1.jar 

Everything works fine, I can see my welcome page on serverIP:port and access my shiny apps, but when I tested the apps, my local files cannot upload.

![Screen Shot 2020-07-03 at 3 28 41 PM](https://user-images.githubusercontent.com/43000714/86443511-f2aa6a80-bd41-11ea-8330-dd57ad6f1956.png)

and what showed in the server is 

_`2020-07-03 15:28:38.726 ERROR **26088** --- [   XNIO-2 I/O-1] io.undertow.proxy                        : UT005028: Proxy request to /proxy_endpoint/d5be59a4-e960-42cc-8db7-e0f9140b45ee/EigenGWASRshiny/session/89a921f7cd2458c5c6a8590a31a2b85a/upload/490f64bd8ee563d9c5190ece failed

java.nio.channels.ClosedChannelException: null
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:188) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:167) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.StreamConnection.invokeCloseListener(StreamConnection.java:80) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.Connection.close(Connection.java:142) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.util.ConnectionUtils.cleanClose(ConnectionUtils.java:83) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection.close(HttpClientConnection.java:466) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$IoExceptionHandler.handleException(ProxyHandler.java:790) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.ChannelListeners.invokeChannelExceptionHandler(ChannelListeners.java:126) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.util.Transfer.initiateTransfer(Transfer.java:67) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:644) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:561) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientExchange.invokeReadReadyCallback(HttpClientExchange.java:212) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection.initiateRequest(HttpClientConnection.java:410) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection.sendRequest(HttpClientConnection.java:343) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction.run(ProxyHandler.java:561) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.util.SameThreadExecutor.execute(SameThreadExecutor.java:35) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.HttpServerExchange.dispatch(HttpServerExchange.java:815) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:316) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:290) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool.connectionReady(ProxyConnectionPool.java:338) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool.access$900(ProxyConnectionPool.java:61) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool$2.completed(ProxyConnectionPool.java:286) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool$2.completed(ProxyConnectionPool.java:273) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider.handleConnected(HttpClientProvider.java:156) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider.access$000(HttpClientProvider.java:51) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider$2.handleEvent(HttpClientProvider.java:127) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider$2.handleEvent(HttpClientProvider.java:124) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:326) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

2020-07-03 15:28:38.729 ERROR **26088** --- [   XNIO-2 I/O-1] io.undertow.proxy                        : UT005028: Proxy request to /proxy_endpoint/d5be59a4-e960-42cc-8db7-e0f9140b45ee/EigenGWASRshiny/session/89a921f7cd2458c5c6a8590a31a2b85a/upload/490f64bd8ee563d9c5190ece failed

java.nio.channels.ClosedChannelException: null
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:188) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:167) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.StreamConnection.invokeCloseListener(StreamConnection.java:80) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.Connection.close(Connection.java:142) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.util.ConnectionUtils.cleanClose(ConnectionUtils.java:83) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection.close(HttpClientConnection.java:466) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$IoExceptionHandler.handleException(ProxyHandler.java:790) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.ChannelListeners.invokeChannelExceptionHandler(ChannelListeners.java:126) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.util.Transfer.initiateTransfer(Transfer.java:67) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:644) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:561) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientExchange.invokeReadReadyCallback(HttpClientExchange.java:212) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection.initiateRequest(HttpClientConnection.java:410) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientConnection.sendRequest(HttpClientConnection.java:343) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction.run(ProxyHandler.java:561) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.util.SameThreadExecutor.execute(SameThreadExecutor.java:35) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.HttpServerExchange.dispatch(HttpServerExchange.java:815) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:316) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:290) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool.connectionReady(ProxyConnectionPool.java:338) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool.access$900(ProxyConnectionPool.java:61) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool$2.completed(ProxyConnectionPool.java:286) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool$2.completed(ProxyConnectionPool.java:273) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider.handleConnected(HttpClientProvider.java:156) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider.access$000(HttpClientProvider.java:51) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider$2.handleEvent(HttpClientProvider.java:127) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.client.http.HttpClientProvider$2.handleEvent(HttpClientProvider.java:124) [undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:326) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]`_

How can I solve the issue? 
Thank you.

**Comment by GuoanQi1996** [comment]
My issue solved by editing Miscellaneous Settings, as my apps need large files upload, so i add the following lines in application.yml.
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

Thank you!
