### ISSUE TITLE
@fmichielssen : disabling HTTP/2 at the load balancer indeed solves the 503 issue, the resources are properly returned then.

### ISSUE THREAD

**Issue by adellam** [openanalytics/shinyproxy#250]
@fmichielssen : disabling HTTP/2 at the load balancer indeed solves the 503 issue, the resources are properly returned then.

The load balancer itself does http1.1 requests towards the Shinyproxy in both cases, it seems as if HTTP/2 is active, then the requests from the load balancer towards Shinyproxy are "too fast" to be handled.

Maybe this is helpful, if HTTP/2 is active, then Shinyproxy reports the following error:
```
2019-04-16 14:08:52.303 ERROR 1 --- [   XNIO-2 I/O-2] org.xnio.nio                             : XNIO000011: Task io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler@60d73b7a failed with an exception

java.lang.IllegalStateException: UT000004: getResponseChannel() has already been called
	at io.undertow.server.HttpServerExchange.addResponseWrapper(HttpServerExchange.java:1463) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.HttpServerExchange.addResponseCommitListener(HttpServerExchange.java:1834) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at eu.openanalytics.containerproxy.util.ProxyMappingManager$1.getConnection(ProxyMappingManager.java:70) ~[containerproxy-0.6.0.jar!/:0.6.0]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.failed(ProxyHandler.java:329) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.queuedRequestFailed(ProxyHandler.java:341) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.ProxyConnectionPool.connect(ProxyConnectionPool.java:531) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at io.undertow.server.handlers.proxy.LoadBalancingProxyClient.getConnection(LoadBalancingProxyClient.java:301) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at eu.openanalytics.containerproxy.util.ProxyMappingManager$1.getConnection(ProxyMappingManager.java:69) ~[containerproxy-0.6.0.jar!/:0.6.0]
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.run(ProxyHandler.java:310) ~[undertow-core-1.4.22.Final.jar!/:1.4.22.Final]
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
```

@shrektan : Sticky session had no effect

_Originally posted by @senfbrot in https://github.com/openanalytics/shinyproxy/issues/65#issuecomment-483686676_

**Comment by adellam** [comment]
Hello all,
I have shinyproxy deployed on premise on a docker-swarm cluster. HAPROXY acts as a reverse proxy before shinyproxy.
HAPROXY has been deployed as described here: https://www.haproxy.com/blog/haproxy-on-docker-swarm-load-balancing-and-dns-service-discovery/ (third scenario)

WIth version 2.3.1 we are suffering the same problems reported in #65, we disabled the http2 support but it made no difference.

With version 2.4.{0,1} shinyproxy just stops answering. It gives no exception, it never recovers: I have to restart the container service to make it work again.

Our running application.yml follows.

Any hint on how to investigate the behaviour?

[application.yml.txt](https://github.com/openanalytics/shinyproxy/files/5604610/application.yml.txt)
.

**Comment by shrektan** [comment]
If you really want this to be resolved soon... I strongly suggest one of you take some time to make a reproducible example as I did [here](https://github.com/shrektan/DT-load-balancer/). It's only so that the author / maintainer of ShinyProxy can reproduce locally thus locate the root cause of issue...

**Comment by adellam** [comment]
> If you really want this to be resolved soon... I strongly suggest one of you take some time to make a reproducible example as I did [here](https://github.com/shrektan/DT-load-balancer/). It's only so that the author / maintainer of ShinyProxy can reproduce locally thus locate the root cause of issue...

Thanks, yes, I'll provide a complete working configuration.

**Comment by adellam** [comment]
I removed haproxy from the equation, and it seems that a specific shiny app that we run make  the whole service hang after some activations. We'll try to debug it and eventually report what we found

**Comment by adellam** [comment]
Sorry, I forgot to update and close the issue!
The application I was talking about required a specific CPU feature that was not supported by the hypervisors that hosted the Docker Swarm cluster.
I started another cluster in a different infrastructure, and the hangs never happened there.
So it was a problem of our infrastructure.

**Comment by LEDfan** [comment]
Thanks for reporting back! It's good to know that these kind of issues exists.
