### ISSUE TITLE
Login Problems on shinyproxy 2.5.0

### ISSUE THREAD

**Issue by Patrikios** [openanalytics/shinyproxy#319]
Created a new debian buster VM in order to test out the newer version 2.5.0 over 2.3.0 which I am using in production envirnoment in LDAP authentification mode, works just fine.

After getting the 2.5.0 service up an running, setting to simple authentification as per the example from your official website, I cannot login.  I get the following error that I do not understand. The error is caused by (futher in the error message)

_**Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)**_

The relevant trace:

```
Aug 25 11:48:11 ias258a java[7303]: 2021-08-25 11:48:11.081  INFO 7303 --- [           main] e.o.c.util.StartupEventListener          : Started ShinyProxy 2.5.0 (ContainerProxy 0.8.8)
Aug 25 11:48:11 ias258a java[7303]: 2021-08-25 11:48:11.735  INFO 7303 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
Aug 25 11:48:11 ias258a java[7303]: 2021-08-25 11:48:11.735  INFO 7303 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
Aug 25 11:48:11 ias258a java[7303]: 2021-08-25 11:48:11.744  INFO 7303 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 9 ms
Aug 25 11:48:18 ias258a java[7303]: 2021-08-25 11:48:18.595  INFO 7303 --- [  XNIO-1 task-1] e.o.containerproxy.service.UserService   : User logged in [user: jack]
Aug 25 11:48:18 ias258a java[7303]: 2021-08-25 11:48:18.609 ERROR 7303 --- [  XNIO-1 task-1] io.undertow.request                      : UT005023: Exception handling request to /login
Aug 25 11:48:18 ias258a java[7303]: java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
Aug 25 11:48:18 ias258a java[7303]: HandlerMethod details:
Aug 25 11:48:18 ias258a java[7303]: Bean [eu.openanalytics.containerproxy.stat.impl.InfluxDBCollector]
Aug 25 11:48:18 ias258a java[7303]: Method [public void eu.openanalytics.containerproxy.stat.impl.AbstractDbCollector.onUserLoginEvent(eu.openanalytics.containerproxy.event.UserLoginEvent) throws java.io.IOException]
Aug 25 11:48:18 ias258a java[7303]: Resolved arguments:
Aug 25 11:48:18 ias258a java[7303]: [0] [type=eu.openanalytics.containerproxy.event.UserLoginEvent] [value=eu.openanalytics.containerproxy.event.UserLoginEvent[source=eu.openanalytics.containerproxy.service.UserService@36a64601]]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:322) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at eu.openanalytics.containerproxy.service.UserService.onAuthenticationSuccessEvent(UserService.java:212) ~[containerproxy-0.8.8.jar!/:0.8.8]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.authentication.DefaultAuthenticationEventPublisher.publishAuthenticationSuccess(DefaultAuthenticationEventPublisher.java:103) ~[spring-security-core-5.3.4.RELEASE.jar!/:5.3.4.R
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:243) ~[spring-security-core-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:219) ~[spring-security-core-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:95) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELE
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:141) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.3.4.RELEASE.jar!/:5.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at eu.openanalytics.containerproxy.util.ProxyMappingManager$ProxyPathHandler.handleRequest(ProxyMappingManager.java:160) ~[containerproxy-0.8.8.jar!/:0.8.8]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) ~[undertow-servlet-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:370) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:836) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
Aug 25 11:48:18 ias258a java[7303]:         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
Aug 25 11:48:18 ias258a java[7303]:         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
Aug 25 11:48:18 ias258a java[7303]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
Aug 25 11:48:18 ias258a java[7303]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]: Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.net.Socket.connect(Socket.java:558) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at eu.openanalytics.containerproxy.stat.impl.InfluxDBCollector.writeToDb(InfluxDBCollector.java:67) ~[containerproxy-0.8.8.jar!/:0.8.8]
Aug 25 11:48:18 ias258a java[7303]:         at eu.openanalytics.containerproxy.stat.impl.AbstractDbCollector.onUserLoginEvent(AbstractDbCollector.java:38) ~[containerproxy-0.8.8.jar!/:0.8.8]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Aug 25 11:48:18 ias258a java[7303]:         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
Aug 25 11:48:18 ias258a java[7303]:         ... 91 common frames omitted
```

Is there something I need to factor in when implementing the 2.5.0 version as compared to 2.3.0?

**Comment by Patrikios** [comment]
It was a problem in application file.

**Comment by johnytr1** [comment]
Do you remember what exactly you changed in application.yml?
