### ISSUE TITLE
Session and App Persistence errors to connect to redis

### ISSUE THREAD

**Issue by robsonyeg** [openanalytics/shinyproxy#410]
Hello,

My deployment environment is docker swarm with Shinyproxy 3.0.1. 

I enabled the session and app persistence with Redis. 
```
  spring:
    session:
      store-type: redis
    redis:
      host: redis
      password: strongpassword
  store-mode: redis
  stop-proxies-on-shutdown: false
```

Redis service is created with Shinyproxy in the same stack. And the name is resolvable from the container of Shinyproxy
```
root@69ec61d87a80:/opt/shinyproxy# ping redis
PING redis (10.0.6.6) 56(84) bytes of data.
64 bytes from 10.0.6.6 (10.0.6.6): icmp_seq=1 ttl=64 time=0.244 ms
64 bytes from 10.0.6.6 (10.0.6.6): icmp_seq=2 ttl=64 time=0.135 ms
64 bytes from 10.0.6.6 (10.0.6.6): icmp_seq=3 ttl=64 time=0.105 ms
```
But the Shinyproxy got error during startup, it reports not able to connect to `localhost`. But the host of redis in configuration  "redis" which does not make sense.

```
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | org.springframework.context.ApplicationContextException: Failed to start bean 'redisContainer'; nested exception is org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
```

Detail error logs is here:
```
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 2023-03-15 19:52:35.005  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 2023-03-15 19:52:35.013  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception thrown from ApplicationListener handling ContextClosedEvent
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@77f80c04 has not been refreshed yet
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1141) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1153) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:371) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:336) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:427) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$CloseManagementContextListener.propagateCloseIfNecessary(ManagementContextAutoConfiguration.java:203) ~[spring-boot-actuator-autoconfigure-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$CloseManagementContextListener.onApplicationFailedEvent(ManagementContextAutoConfiguration.java:198) ~[spring-boot-actuator-autoconfigure-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$CloseManagementContextListener.onApplicationEvent(ManagementContextAutoConfiguration.java:189) ~[spring-boot-actuator-autoconfigure-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:162) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.context.event.EventPublishingRunListener.failed(EventPublishingRunListener.java:136) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplicationRunListeners.callFailedListener(SpringApplicationRunListeners.java:96) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplicationRunListeners.lambda$failed$7(SpringApplicationRunListeners.java:87) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplicationRunListeners.failed(SpringApplicationRunListeners.java:86) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:781) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at eu.openanalytics.containerproxy.ContainerProxyApplication.main(ContainerProxyApplication.java:128) ~[containerproxy-1.0.1.jar!/:1.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 2023-03-15 19:52:35.018  INFO 1 --- [           main] io.undertow                              : stopping server: Undertow - 2.2.21.Final
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 2023-03-15 19:52:35.039 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | org.springframework.context.ApplicationContextException: Failed to start bean 'redisContainer'; nested exception is org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at eu.openanalytics.containerproxy.ContainerProxyApplication.main(ContainerProxyApplication.java:128) ~[containerproxy-1.0.1.jar!/:1.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[shinyproxy.jar:3.0.1]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | Caused by: org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:275) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.listener.RedisMessageListenerContainer.start(RedisMessageListenerContainer.java:249) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.24.jar!/:5.3.24]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	... 18 common frames omitted
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | Caused by: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException(LettuceConnectionFactory.java:1689) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1597) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1383) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1366) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:1093) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:421) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.listener.RedisMessageListenerContainer$Subscriber.initialize(RedisMessageListenerContainer.java:1186) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.listener.RedisMessageListenerContainer.doSubscribe(RedisMessageListenerContainer.java:318) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:295) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:265) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	... 20 common frames omitted
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:330) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.lettuce.core.RedisClient.connect(RedisClient.java:216) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1595) ~[spring-data-redis-2.7.6.jar!/:2.7.6]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	... 28 common frames omitted
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | Caused by: java.net.ConnectException: Connection refused
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:666) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.86.Final.jar!/:4.1.86.Final]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]
shiny_shiny.1.r5f9jv7ll1kz@node01.example.com   | 

```

Please help to take a look.

Thanks,

Robin

**Comment by LEDfan** [comment]
Hi, the sections with `spring` settings should not be nested under the `proxy` settings, so you should have something like:


```yaml
spring:
    session:
      store-type: redis
    redis:
      host: redis
      password: strongpassword
proxy:
  store-mode: redis
  stop-proxies-on-shutdown: false
```

I'll update the documentation to make this more clear.

**Comment by robsonyeg** [comment]
@LEDfan, yes, it works as you said. 

Another question, For this HA setup, when I restart the Shinyproxy service from docker swarm, the running app will stop working (grey out due to Websocket connection failure). Is this something expected behaviour? 

I do notice that the background service for the app is still alive, and if the user refreshes the page, the user will continue to use the app from the previous service created by Shintyproxy.

Thanks,
Robin

**Comment by LEDfan** [comment]
Hi, indeed the websocket connection will always gets disconnected if the underlying server is stopped. This is something we cannot fix. However, you can tell ShinyProxy to re-connect the websocket connection when the server has started up again, see: https://shinyproxy.io/documentation/ui/#automatically-reconnecting-websockets

**Comment by robsonyeg** [comment]
I got it. I appreciate the clarification. @LEDfan
