### ISSUE TITLE
Error about java IllegalArgumentException

### ISSUE THREAD

**Issue by fang19911030** [openanalytics/shinyproxy#443]
I am a new user of shinyproxy, I notice this error in the log. But I don't know what is the reason for this.  The shinyproxy itself works well, at least for the demo apps. I am using the default fallback configuration file. Thank you for your help.

```
2023-08-22 14:59:18.709  INFO 316932 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2023-08-22 14:59:18.738  INFO 316932 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2023-08-22 14:59:19.050  INFO 316932 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 238 ms. Found 0 Redis repository interfaces.
2023-08-22 14:59:19.597  INFO 316932 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2023-08-22 14:59:19.640  INFO 316932 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2023-08-22 14:59:22.044  INFO 316932 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-08-22 14:59:22.115  INFO 316932 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-08-22 14:59:24.169  WARN 316932 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-08-22 14:59:24.366  INFO 316932 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-08-22 14:59:24.373  INFO 316932 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 11865 ms
2023-08-22 14:59:25.759  INFO 316932 --- [           main] e.o.c.service.IdentifierService          : ShinyProxy runtimeId:                   641a0b8f-3096-48b2-8384-f64ada8b9c9b
2023-08-22 14:59:26.016  INFO 316932 --- [           main] e.o.c.service.IdentifierService          : ShinyProxy instanceID (hash of config): 10fbf56b3e47d94f25e0bdfb7f71f4c37aa874e1
2023-08-22 14:59:28.350  INFO 316932 --- [           main] o.s.boot.web.servlet.RegistrationBean    : Filter orderedFormContentFilter was not registered (disabled)
2023-08-22 14:59:29.777  INFO 316932 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@14bf57b2, org.springframework.security.web.session.ForceEagerSessionCreationFilter@46d9aec8, org.springframework.security.web.session.ForceEagerSessionCreationFilter@5e1218b4, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@14379273, org.springframework.security.web.context.SecurityContextPersistenceFilter@12958360, org.springframework.security.web.header.HeaderWriterFilter@6f0cb5a1, org.springframework.security.web.csrf.CsrfFilter@3162743f, org.springframework.security.web.authentication.logout.LogoutFilter@748e9b20, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@1cc9cfb2, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@7918c7f8, eu.openanalytics.containerproxy.util.AppRecoveryFilter@1d782abe, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@6f3f0fae, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@63fdffcd, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@17740dae, org.springframework.security.web.session.SessionManagementFilter@47547132, org.springframework.security.web.access.ExceptionTranslationFilter@4e92466a, eu.openanalytics.shinyproxy.AuthenticationRequiredFilter@1c504e66, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@16073fa8]
2023-08-22 14:59:29.863  WARN 316932 --- [           main] org.thymeleaf.templatemode.TemplateMode  : [THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2023-08-22 14:59:31.145  INFO 316932 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2023-08-22 14:59:35.596  INFO 316932 --- [           main] o.s.l.c.support.AbstractContextSource    : Property 'userDn' not set - anonymous context will be used for read-write operations
2023-08-22 14:59:36.601  INFO 316932 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2023-08-22 14:59:36.612  INFO 316932 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'ShinyProxy.errorChannel' has 1 subscriber(s).
2023-08-22 14:59:36.613  INFO 316932 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2023-08-22 14:59:36.637  INFO 316932 --- [           main] io.undertow                              : starting server: Undertow - 2.2.21.Final
2023-08-22 14:59:36.680  INFO 316932 --- [           main] org.xnio                                 : XNIO version 3.8.8.Final
2023-08-22 14:59:36.736  INFO 316932 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.8.Final
2023-08-22 14:59:37.050  INFO 316932 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2023-08-22 14:59:37.249  INFO 316932 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8080 (http)
2023-08-22 14:59:37.580  INFO 316932 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-08-22 14:59:37.580  INFO 316932 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 310 ms
2023-08-22 14:59:37.613  INFO 316932 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2023-08-22 14:59:39.151  INFO 316932 --- [           main] io.undertow                              : starting server: Undertow - 2.2.21.Final
2023-08-22 14:59:39.164  INFO 316932 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 9090 (http)
2023-08-22 14:59:39.254  INFO 316932 --- [           main] e.o.c.util.StartupEventListener          : Started ShinyProxy 3.0.2 (ContainerProxy 1.0.2)
2023-08-22 14:59:39.255  INFO 316932 --- [           main] e.o.c.service.AppRecoveryService         : Recovery of running apps disabled
2023-08-22 15:00:03.379  INFO 316932 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-08-22 15:00:03.384  INFO 316932 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-08-22 15:00:03.392  INFO 316932 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2023-08-22 15:00:12.768  INFO 316932 --- [  XNIO-1 task-6] e.o.containerproxy.service.UserService   : User logged in [user: jack]
2023-08-22 15:00:19.932 ERROR 316932 --- [   XNIO-1 I/O-2] io.undertow.request                      : UT005071: Undertow request failed HttpServerExchange{ CONNECT ip138.com:443}

java.lang.IllegalArgumentException: UT000068: Servlet path match failed
	at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:83) ~[undertow-servlet-2.2.21.Final.jar!/:2.2.21.Final]
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:133) ~[undertow-servlet-2.2.21.Final.jar!/:2.2.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:147) ~[undertow-servlet-2.2.21.Final.jar!/:2.2.21.Final]
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:69) ~[undertow-core-2.2.21.Final.jar!/:2.2.21.Final]
	at org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory$DeploymentManagerHandler.handleRequest(DeploymentManagerHttpHandlerFactory.java:75) ~[spring-boot-2.7.6.jar!/:2.7.6]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391) ~[undertow-core-2.2.21.Final.jar!/:2.2.21.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256) ~[undertow-core-2.2.21.Final.jar!/:2.2.21.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.2.21.Final.jar!/:2.2.21.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59) ~[undertow-core-2.2.21.Final.jar!/:2.2.21.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) ~[xnio-nio-3.8.8.Final.jar!/:3.8.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) ~[xnio-nio-3.8.8.Final.jar!/:3.8.8.Final]
```

**Comment by fang19911030** [comment]
It seems this is something random, thus I close the issue.

**Comment by LEDfan** [comment]
For your information: if this server is connected to the internet, I think this might be caused by someone probing your server. Unfortunately, it is common for server on the internet to get daily scans, probes or even attack-attempts. Usually this also involves invalid requests. 
In case you are running a proxy or loadbalancer in front of your server and this error occurs again, it could be useful to check the logs of the proxy and try to find out what request caused this error. We then could have a look in order to fix this error (if any) or just live with the message.
