### ISSUE TITLE
Swarm container did not start in time

### ISSUE THREAD

**Issue by Rosalien** [openanalytics/shinyproxy#470]
Hi !

Thank you so much for your repo and documentation, shinyproxy is a very powerful on deploying R-shiny apps

I am using shinyproxy (lastest 3.0.2) with docker swarm (3 manager). All R-shiny images are stored in a private registry docker. Application.yml is configured to pull image from this registry docker with a large timeout (`container-wait-time: 6000000`).

Sometimes shinyproxy manages to pull images and sometimes it doesn't with this message : `Swarm container did not start in time`. In this case, the message "Failed to start app" appear after about 60 seconds. Which makes me think there's a problem with application.yml configuration.

Also, when I create manually the service 'docker service create --replicas 1 --with-registry-auth --name test my.private.registry/myapp:latest', docker pull work fine.

This is the relevant part of my **application.yml**:

```
server:
  useForwardHeaders: true
  contextPath: /apps
  servlet:
    context-path: /apps

proxy:
  title: xxxxxx
  landing-page: /
  hide-navbar: true
  heartbeat-timeout: -1
  container-wait-time: 6000000
  default-proxy-max-lifetime: -1
  port: 8080
  authentication: ldap
  spring:
    servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB
  server:
    servlet.session.timeout: 7200
  ldap:
    url: xxxxxxx
    manager-dn: xxxxxxx
    manager-password: xxxxxxx
    user-search-filter: xxxxxxx
    group-search-filter: xxxxxxx
    group-search-base: xxxxxxx

  container-backend: docker-swarm
  docker:
    container-network: shinyproxy_sp-net
    internal-networking: true
    image-pull-policy: Always

  specs:
  - id: xxxxxxx
    display-name: xxxxxxx
    description: xxxxxxx
    container-cmd: xxxxxxx
    container-image: xxxxxxx
    docker-registry-username: xxxxxxx
    docker-registry-password: xxxxxxx
    docker-registry-domain: xxxxxxx
    container-network: shinyproxy_sp-net
    container-env-file: .Renviron
```

And **log message** :

```
2024-01-08 14:05:24.990  WARN 1 --- [pool-2-thread-3] e.o.containerproxy.service.ProxyService  : [user=xxxxproxyId=87162f56-1dc7-4762-bc45-29703209480b specId=myapp] Error while stopping failed proxy
eu.openanalytics.containerproxy.ProxyFailedToStartException: Container with index 0 failed to start
	at eu.openanalytics.containerproxy.backend.AbstractContainerBackend.startProxy(AbstractContainerBackend.java:116) ~[containerproxy-1.0.2.jar!/:1.0.2]
	at eu.openanalytics.containerproxy.service.ProxyService.startOrResumeProxy(ProxyService.java:455) ~[containerproxy-1.0.2.jar!/:1.0.2]
	at eu.openanalytics.containerproxy.service.ProxyService.lambda$startProxy$4(ProxyService.java:279) ~[containerproxy-1.0.2.jar!/:1.0.2]
	at eu.openanalytics.containerproxy.service.ProxyService.lambda$action$11(ProxyService.java:599) ~[containerproxy-1.0.2.jar!/:1.0.2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: eu.openanalytics.containerproxy.ContainerFailedToStartException: Swarm container did not start in time
	at eu.openanalytics.containerproxy.backend.docker.DockerSwarmBackend.startContainer(DockerSwarmBackend.java:213) ~[containerproxy-1.0.2.jar!/:1.0.2]
	at eu.openanalytics.containerproxy.backend.AbstractContainerBackend.startProxy(AbstractContainerBackend.java:108) ~[containerproxy-1.0.2.jar!/:1.0.2]
	... 8 common frames omitted
```

Thanks in advance for your help !

**Comment by Rosalien** [comment]
Here message log from `sudo journalctl -u docker -d` :

```
Jan 09 10:32:20 xxxxxxxxxxxxx dockerd[1422295]: time="2024-01-09T10:32:20.705777114Z" level=info msg="initialized VXLAN UDP port to 5789 "
Jan 09 10:33:23 xxxxxxxxxxxxx dockerd[1422295]: time="2024-01-09T10:33:23.698325466Z" level=warning msg="failed to deactivate service binding for container sp-service-1df3aaff-5ad8-46ba-b092-e4dcd5340090.1.lksys3hucb2bbena5phry7fzf" error="No such container: sp-service-1df3aaff-5ad8-46ba-b092-e4dcd5340090.1.lksys3hucb2bbena5phry7fzf" module=node/agent/taskmanager node.id=w70z0ws8q0xqfy3xqg75pfi6d service.id=yyi2u81dggp6uxswmmi3mn4xh task.id=lksys3hucb2bbena5phry7fzf
Jan 09 10:33:23 xxxxxxxxxxxxx dockerd[1422295]: time="2024-01-09T10:33:23.698454372Z" level=error msg="Not continuing with pull after error: context canceled"
Jan 09 10:33:25 xxxxxxxxxxxxx dockerd[1422295]: time="2024-01-09T10:33:25.923814203Z" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint l80nyas411nwi123zkpfa8n9s e3ddd4512beec8092deae9fc156068c63874ab64a366b3b198c6f441457280ee], retrying...."
Jan 09 10:33:25 xxxxxxxxxxxxx dockerd[1422295]: time="2024-01-09T10:33:25.948973785Z" level=error msg="failed removing service binding for b428b780ef461c99c10dcc0d65ef4a7500c520d490288383932e7b9f2ef541c1 epRec:{shinyproxy_shinyproxy.1.x923tqkz24iwdqpsn4l7f273d shinyproxy_shinyproxy l8q43pem40qjx3ypvskqylai8 10.0.4.11 10.0.4.69 [] [shinyproxy] [0def030aa614] false} err:network l80nyas411nwi123zkpfa8n9s not found"
```

**Comment by LEDfan** [comment]
Hi @Rosalien 

Thank you for looking into this! We will make this timeout configurable in the next release. This is already the case for the Kubernetes backend, but it seems we never implemented this for the Docker swarm backend.

**Comment by Rosalien** [comment]
Ok, thanks you !!
