### ISSUE TITLE
issues when upgrading from version 3.0.2 to 3.1.0

### ISSUE THREAD

**Issue by PauloJhonny** [openanalytics/shinyproxy#492]
Hi, 

Firstly, I would like to thank you for the shinyproxy version upgrade.

However, when trying to change from version 3.0.2 to 3.1.0, my applications stopped working completely. I can go to the index page, but when I try to access the applications a blank page appears and the following happens in the logs:

_2024-05-10T18:00:31.349Z  WARN 1 --- [XNIO-1 task-6] actStandardFragmentInsertionTagProcessor : [THYMELEAF][XNIO-1 task-6][app] Deprecated unwrapped fragment expression "../fragments/navbar :: navbar" found in template app, line 84, col 7. Please use the complete syntax of fragment expressions instead ("~{../fragments/navbar :: navbar}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-05-10T18:00:32.693Z  WARN 1 --- [XNIO-1 task-5] actStandardFragmentInsertionTagProcessor : [THYMELEAF][XNIO-1 task-5][app] Deprecated unwrapped fragment expression "../fragments/navbar :: navbar" found in template app, line 84, col 7. Please use the complete syntax of fragment expressions instead ("~{../fragments/navbar :: navbar}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-05-10T18:00:33.341Z ERROR 1 --- [XNIO-1 I/O-7] io.undertow.proxy                        : UT005028: Proxy request to /s3i/proxy_endpoint/67d42724-f5b3-48b2-89f7-59a4a30c6a71/ failed

java.nio.channels.ClosedChannelException: null
        at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:198) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:177) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.StreamConnection.invokeCloseListener(StreamConnection.java:132) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.Connection.close(Connection.java:142) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.IoUtils.safeClose(IoUtils.java:152) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at io.undertow.util.ConnectionUtils.doDrain(ConnectionUtils.java:130) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at io.undertow.util.ConnectionUtils.cleanClose(ConnectionUtils.java:74) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at io.undertow.client.http.HttpClientConnection.close(HttpClientConnection.java:491) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at org.xnio.IoUtils.safeClose(IoUtils.java:152) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at io.undertow.server.handlers.proxy.ProxyHandler$IoExceptionHandler.handleException(ProxyHandler.java:833) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at org.xnio.ChannelListeners.invokeChannelExceptionHandler(ChannelListeners.java:126) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at io.undertow.util.Transfer$TransferListener.handleEvent(Transfer.java:193) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at io.undertow.channels.DetachableStreamSourceChannel$SetterDelegatingListener.handleEvent(DetachableStreamSourceChannel.java:228) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at io.undertow.channels.DetachableStreamSourceChannel$SetterDelegatingListener.handleEvent(DetachableStreamSourceChannel.java:215) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) ~[xnio-nio-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) ~[xnio-nio-3.8.8.Final.jar!/:3.8.8.Final]

2024-05-10T18:00:34.784Z ERROR 1 --- [XNIO-1 I/O-4] io.undertow.proxy                        : UT005028: Proxy request to /s3i/proxy_endpoint/67d42724-f5b3-48b2-89f7-59a4a30c6a71/ failed

java.nio.channels.ClosedChannelException: null
        at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:198) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:177) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.StreamConnection.invokeCloseListener(StreamConnection.java:132) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.Connection.close(Connection.java:142) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at org.xnio.IoUtils.safeClose(IoUtils.java:152) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
        at io.undertow.util.ConnectionUtils.doDrain(ConnectionUtils.java:130) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at io.undertow.util.ConnectionUtils.cleanClose(ConnectionUtils.java:74) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at io.undertow.client.http.HttpClientConnection.close(HttpClientConnection.java:491) ~[undertow-core-2.3.10.Final.jar!/:2.3.10.Final]
        at org.xnio.IoUtils.safeClose(IoUtils.java:152) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]_

In our case, we customized all html files: admin.html, app.html, index.html and login.html. In this sense, I would like to know if there were many changes in these files from version 3.0.2 to 3.1.0. I don't know if that would be the problem.

Could you help me, please?

Thank you very much.

**Comment by PauloJhonny** [comment]
I noticed that the shinyproxy docker container is not working and keeps restarting.

`
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                          PORTS               NAMES
d83719216064        datanovia/shinyproxy     "java -jar /opt/shin…"   3 minutes ago       Restarting (1) 20 seconds ago                       dnv_shinyproxy
`

I tried to see the logs using the command below:

`sudo docker logs --tail 50 --follow --timestamps d83719216064`

And this information appeared:

`
2024-05-10T15:05:15.344607252Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2024-05-10T15:05:15.344614599Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2024-05-10T15:05:15.344618949Z 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2024-05-10T15:05:15.344624164Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2024-05-10T15:05:15.344628561Z 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
2024-05-10T15:06:07.714961001Z Error: A JNI error has occurred, please check your installation and try again
2024-05-10T15:06:07.715356599Z Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2024-05-10T15:06:07.715434486Z 	at java.lang.ClassLoader.defineClass1(Native Method)
2024-05-10T15:06:07.715477729Z 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
2024-05-10T15:06:07.715500622Z 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2024-05-10T15:06:07.715529452Z 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
2024-05-10T15:06:07.715548174Z 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2024-05-10T15:06:07.715578899Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2024-05-10T15:06:07.715595716Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2024-05-10T15:06:07.715626225Z 	at java.security.AccessController.doPrivileged(Native Method)
2024-05-10T15:06:07.715676845Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2024-05-10T15:06:07.715682853Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2024-05-10T15:06:07.715697603Z 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2024-05-10T15:06:07.715777790Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2024-05-10T15:06:07.715784051Z 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
2024-05-10T15:07:08.866073027Z Error: A JNI error has occurred, please check your installation and try again
2024-05-10T15:07:08.866490891Z Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2024-05-10T15:07:08.866542043Z 	at java.lang.ClassLoader.defineClass1(Native Method)
2024-05-10T15:07:08.866598289Z 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
2024-05-10T15:07:08.866612063Z 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2024-05-10T15:07:08.866619482Z 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
2024-05-10T15:07:08.866664755Z 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2024-05-10T15:07:08.866675292Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2024-05-10T15:07:08.866710495Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2024-05-10T15:07:08.866749377Z 	at java.security.AccessController.doPrivileged(Native Method)
2024-05-10T15:07:08.866780671Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2024-05-10T15:07:08.866808557Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2024-05-10T15:07:08.866841885Z 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2024-05-10T15:07:08.866886731Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2024-05-10T15:07:08.866919793Z 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
2024-05-10T15:08:10.040837836Z Error: A JNI error has occurred, please check your installation and try again
2024-05-10T15:08:10.041325165Z Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2024-05-10T15:08:10.041437142Z 	at java.lang.ClassLoader.defineClass1(Native Method)
2024-05-10T15:08:10.041482596Z 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
2024-05-10T15:08:10.041516128Z 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2024-05-10T15:08:10.041551603Z 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
2024-05-10T15:08:10.041578715Z 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2024-05-10T15:08:10.041616119Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2024-05-10T15:08:10.041645125Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2024-05-10T15:08:10.041697842Z 	at java.security.AccessController.doPrivileged(Native Method)
2024-05-10T15:08:10.041702906Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2024-05-10T15:08:10.041756789Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2024-05-10T15:08:10.041780224Z 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2024-05-10T15:08:10.041834590Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2024-05-10T15:08:10.041874969Z 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
`

If anyone can help me decipher the problem, I would be grateful.
