### ISSUE TITLE
Reactable elements not loading

### ISSUE THREAD

**Issue by jkkbuddika** [openanalytics/shinyproxy#518]
Hello,

In the last few days I ran into this issue where certain reactable elements do not get loaded when a Docker based shiny application is deployed using Shinyproxy. The same image locally compiles the UI with no issues with all elements, however certain tables, etc. are missing in the Shinyproxy deployment. When I checked the browser console I see this error message:

```
TypeError: Cannot read properties of undefined (reading 'hydrate')
    at e.map.t.Header (columns.js:287:20)
    at Reactable.js:772:26
    at Array.map (<anonymous>)
    at Reactable.js:764:32
    at Array.map (<anonymous>)
    at Ol (Reactable.js:757:34)
    at of (react-dom.min.js:109:301)
    at Rk (react-dom.min.js:250:214)
    at Si (react-dom.min.js:195:185)
    at Pk (react-dom.min.js:195:116)
```

An example snippet looks like this:

```R
overall_tableUI <- function(id) {
  ns <- NS(id)
  tagList(
    tags$span(style = "text-align: center;",
              reactableOutput(ns('mini_table')))))} overall_tableSERVER <- function(id, data, lot_names) {
  moduleServer(id, function(input, output, session) {stats_df <- do.call(rbind, stats_list)
    stats_df <- t(as.data.frame(stats_df))
    colnames(stats_df) <- lot_names()

    output$mini_table <- renderReactable({
      reactable(data = stats_df,
                bordered= FALSE,
                searchable = FALSE,
                rownames = TRUE,
                showPageSizeOptions = FALSE,
                highlight = TRUE,
                striped = FALSE,
                showSortIcon = FALSE,
                showSortable=FALSE, 
                fullWidth = FALSE,
                width = "500px")
    }))}
    ...
```

Any thoughts on why this is happening and a way to resolve this issue? Thanks in advance. Please let me know if you need more information.

**Comment by flash0926** [comment]
install reactR to version 0.5.0

**Comment by jkkbuddika** [comment]
Thanks @flash0926. This solved my issue!
